MOVE_MODE_WALK = "WALK"
MOVE_MODE_JUMP = "JUMP"

POINT_TYPE_PASS = "PASS"
POINT_TYPE_TARGET = "TARGET"

ACTION_TELEPORT = "TELEPORT"
ACTION_MACRO = "MACRO"
ACTION_PICK_UP = "PICK_UP"
ACTION_CATCH_INSECT = "CATCH_INSECT"
ACTION_CLEAN_ANIMAL = "CLEAN_ANIMAL"
ACTION_FISHING = "FISHING"
ACTION_WAIT = "WAIT"
ACTION_KEY_CLICK = "KEY_CLICK"

ACTION_MINIGAME = "MINIGAME"
ACTION_GROUP_CHAT = "GROUP_CHAT"
ACTION_PLACE_ITEM = "PLACE_ITEM"
ACTION_CHANGE_MUSIC = "CHANGE_MUSIC"